### ISSUE TITLE
Profile picture upload

### ISSUE THREAD

**Issue by tilersmyth** [tilersmyth/newstand#4]
Need ability to upload images for locally authenticated accounts and publisher profile accounts. Looking for S3 storage with sensitive API vars stored in .env file.

**Comment by billbarni** [comment]
https://github.com/efstathiosntonas/ngx-form

This project has a solution for that and keeps it free from external paid services. Im trying to learn TypeScript enough so I can help you out.

**Comment by tilersmyth** [comment]
@billbarni thanks for looking into this. I think there might be a more simple, light-weight approach to this than https://github.com/efstathiosntonas/ngx-form. 

I implemented a solution in my last project that might work. It was done in AngularJS 1.6, but I'm sure mirroring in Angular (2) wouldn't be overly burdensome. I'll walk through what i did below to and you can let me know if this sounds like a valid approach. 

1. As you can see [here](https://github.com/tilersmyth/peruse-dev/blob/master/client/components/modal/image-upload-modal.html), I used [ ng-file-upload](https://github.com/danialfarid/ng-file-upload) mostly to validate the request and pass the required data to the controller - [here](https://github.com/tilersmyth/peruse-dev/blob/master/client/app/admin/settings/image-upload-modal.controller.js#L24), which then sent it to the server. We could potentially use something like [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) or [ng2-file-uploader](https://github.com/spartaksun/ng2-file-uploader) for this part of the solution.

2. On the server side it was handled [here](https://github.com/tilersmyth/peruse-dev/blob/master/server/api/site/site.controller.js#L564) and making use of the these [imported services](https://github.com/tilersmyth/peruse-dev/blob/master/server/api/site/site.controller.js#L30-L41)  - with the exception of line 35 - 37. It was actually quite easy working with Amazon S3 and costs next to nothing (actually nothing for new sign-ups - https://aws.amazon.com/s3/pricing/).

Let me know if any of this makes sense to you. Definitely open to other ideas, but I had luck with the aforementioned implementation and found it be actually pretty simple once I put the pieces together.
